version: '2'

volumes:
  nifi:
    external: true

services:
  kafka:
    image: ches/kafka 
    build: ../docker-kafka
    links:
      - zoo 
        #extends:
        #file: ./nifi-container/docker-compose.yml
        #service: nifi
    environment:
       ZOOKEEPER_CONNECTION_STRING: zoo:2181
    ports:
      - "9092:9092"
  
  zoo:
    image: zookeeper
    container_name: zoo
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888
      ZOOKEEPER_CONNECTION_STRING: zoo:2181
  
  nifi-sp:  
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8010:8080"
    environment:
      - NIFI_PROFILE=nifi-sp

  nifi-ss:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8410:8443"
    environment:
      - NIFI_HOSTNAME=nifi-ss

  nifi-cp:
    container_name: nifi-cp
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8010:8080"
    depends_on:
      - zoo
      - kafka
    links:
      - kafka
    environment:
      - NIFI_PROFILE=nifi-cp

  nifi-cp-nodes:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - nifi-cp
    environment:
      - NIFI_PROFILE=nifi-cp

  nifi-cs1:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8420:8443"
    depends_on:
      - zoo
    environment:
      - NIFI_HOSTNAME=nifi-cs1

  nifi-cs2:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - zoo
    environment:
      - NIFI_HOSTNAME=nifi-cs2

  nifi-cs3:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - zoo
    environment:
      - NIFI_HOSTNAME=nifi-cs3
